<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMSMAPPING [<!ELEMENT JMSMAPPING (target)*>
<!ELEMENT target (id,class,method)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT method (#PCDATA)>
]>
<JMSMAPPING>
	<!--  Do not Modify / IT Arch -->
	<target>
		<id>JMS_TYPE_FAXS</id>
		<class>com.hanjin.framework.component.fax.dao.FaxsEAIDAO</class>
		<method>receiveFaxsQueue</method>
	</target>
	<target>
		<id>JMS_TYPE_MAILS</id>
		<class>com.hanjin.framework.component.common.mail.MailsProxy</class>
		<method>receiveMailsQueue</method>
	</target>
	<target>
		<id>JMS_TYPE_FTPS</id>
		<class>com.hanjin.framework.component.ftp.servicesio.FtpsProxy</class>
		<method>receiveFtpsQueue</method>
	</target>
	<!--  For Remote Server Back End Work  -->
	<target>
		<id>COM001-0002</id>
		<class>com.hanjin.framework.component.backend.core.WorkOnLongTxRemoteServerJMSProxy</class>
		<method>receiveWorkOnLongTx</method>
	</target>
	<!--  Do not Modify / IT Arch -->
	<!-- ===================== MDM ===================== -->

	<target>
		<id>MDM001-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCustomer</method>
	</target>
	<target>
		<id>MDM002-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCrmCustomerReject</method>
	</target>
	<target>
		<id>MDM003-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCustAddr</method>
	</target>
	<target>
		<id>MDM004-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSlsRep</method>
	</target>
	<target>
		<id>MDM005-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmTrade</method>
	</target>
	<target>
		<id>MDM006-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSubTrd</method>
	</target>
	<target>
		<id>MDM007-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVslSvcLaneGeneral</method>
	</target>
	<target>
		<id>MDM009-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmRevLane</method>
	</target>

	<target>
		<id>MDM010-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmGrpCmdt</method>
	</target>
	<target>
		<id>MDM011-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmRepCmdt</method>
	</target>
	<target>
		<id>MDM012-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCommodity</method>
	</target>
	<target>
		<id>MDM017-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCrCust</method>
	</target>
	<target>
		<id>MDM018-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCustPerfGrp</method>
	</target>
	<target>
		<id>MDM019-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVendor</method>
	</target>
	<target>
		<id>MDM020-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCntrVndrClss</method>
	</target>
	<target>
		<id>MDM021-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVendorCustomerGeneral</method>
	</target>
	<target>
		<id>MDM022-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVndrCntcPnt</method>
	</target>
	<target>
		<id>MDM025-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVslCntr</method>
	</target>
	<target>
		<id>MDM027-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmOrganization</method>
	</target>
	<target>
		<id>MDM029-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmYard</method>
	</target>
	<target>
		<id>MDM031-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmLocation</method>
	</target>
	<target>
		<id>MDM032-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCountry</method>
	</target>
	<target>
		<id>MDM033-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmRegion</method>
	</target>
	<target>
		<id>MDM034-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCurrency</method>
	</target>
	<target>
		<id>MDM035-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCharge</method>
	</target>
	<target>
		<id>MDM036-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmAccount</method>
	</target>
	<target>
		<id>MDM037-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmEqOrzCht</method>
	</target>
	<target>
		<id>MDM038-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmRepChg</method>
	</target>
	<target>
		<id>MDM040-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSvcScp</method>
	</target>
	<target>
		<id>MDM041-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSvcScpLane</method>
	</target>
	<target>
		<id>MDM042-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSvcScpLmt</method>
	</target>
	<target>
		<id>MDM043-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCstmsPckTp</method>
	</target>
	<target>
		<id>MDM044-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmPckTp</method>
	</target>
	<target>
		<id>MDM045-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmState</method>
	</target>
	<target>
		<id>MDM046-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmContinent</method>
	</target>
	<target>
		<id>MDM047-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSubcontinent</method>
	</target>
	<target>
		<id>MDM048-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmActivity</method>
	</target>
	<target>
		<id>MDM049-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmMvmtSts</method>
	</target>
	<target>
		<id>MDM050-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmZone</method>
	</target>
	<target>
		<id>MDM051-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmZnDtl</method>
	</target>
	<target>
		<id>MDM052-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCntrSz</method>
	</target>
	<target>
		<id>MDM053-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCntrTp</method>
	</target>
	<target>
		<id>MDM054-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCntrTySz</method>
	</target>
	<target>
		<id>MDM055-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmLseCoYd</method>
	</target>
	<target>
		<id>MDM056-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmSvcScpGeneral</method>
	</target>
	<target>
		<id>MDM057-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmZnGeneral</method>
	</target>
	<target>
		<id>MDM059-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVendorEtc</method>
	</target>
	
	<!-- 2015/06/08 Request by You-Mok Lee (GSA2) -->
	<target>
		<id>MDM063_0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCustRep</method>
	</target>
	<!-- ===================== MDM ===================== -->

	<target>
		<id>FNS047-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageGlMonXchRt</method>
	</target>

	<target>
		<id>FNS009-0001</id>
		<class>com.hanjin.apps.alps.cps.gem.servicesio.GEMPlanningPerformanceJMSProxy</class>
		<method>fNS0090001ReceiveJMS</method>
	</target>
	<target>
		<id>FNS003-0001</id>
		<class>com.hanjin.apps.alps.cps.gem.servicesio.GEMPlanningPerformanceJMSProxy</class>
		<method>fNS0030001ReceiveJMS</method>
	</target>
	<target>
		<id>FNS061_0001</id>
		<class>com.hanjin.apps.alps.cps.gem.servicesio.GEMPlanningPerformanceJMSProxy</class>
		<method>fNS0610001ReceiveJMS</method>
	</target>

	<target>
		<id>FNS056-0001</id>
		<class>com.hanjin.apps.alps.esm.fms.servicesio.TCharterIOInvoiceJMSProxy</class>
		<method>manageOwnerAccountInterface</method>
	</target>

	<target>
		<id>UBIZHJS_ALPSBKG_NACCS</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsbkgNaccsReceiveMQ</method>
	</target>

	<target>
		<id>UBIZHJS_ALPSBKG_ROCS_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsbkgRocsReceiveMQ</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_SLKCUS_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsbkgSlkCusReceiveMQ</method>
	</target>

	<target>
		<id>UBIZHJS_ALPSBKG_ANRACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsbkgAncsReceiveMQ</method>
	</target>

	<target>
		<id>ESM071_0001</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.InboundDocumentationProxy</class>
		<method>receiveOtsInfo</method>
	</target>

	<target>
		<id>ALPSBKG_UBIZHJS_EDO</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.InboundDocumentationProxy</class>
		<method>receiptEdo</method>
	</target>

	<target>
		<id>FNS043-0001</id>
		<class>com.hanjin.apps.alps.fns.inv.servicesio.AccountReceivableInvoiceMasterDataMgtJMSProxy</class>
		<method>createRevenueAccountList</method>
	</target>

	<target>
		<id>ESM066_0001</id>
		<class>com.hanjin.apps.alps.esm.fms.servicesio.TCharterIOInvoiceJMSProxy</class>
		<method>manageOffHireExpenseInterface</method>
	</target>

	<target>
		<id>ESM074_0001</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>loadVslCertiExpDt</method>
	</target>

	<target>
		<id>UBIZHJS_ALPSBKG_IB</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.EBookingConductMQProxy</class>
		<method>receiptXterRqst</method>
	</target>

	<target>
		<id>UBIZHJS_ALPSBKG_HJTBKG</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.GeneralBookingConductMQProxy</class>
		<method>receiptHjtTroEdiAck</method>
	</target>


	<target>
		<id>CMS007_0001</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.BKGPlanningPerformanceJMSProxy</class>
		<method>customerSalesRep</method>
	</target>

	<target>
		<id>CMS011_0001</id>
		<class>com.hanjin.apps.alps.esm.pri.servicesio.PRIMasterDataJMSProxy</class>
		<method>receiveCRMSalesLead</method>
	</target>

	<target>
		<id>CMS012_0001</id>
		<class>com.hanjin.apps.alps.esm.pri.servicesio.PRIMasterDataJMSProxy</class>
		<method>receiveCRMKeyman</method>
	</target>
	<target>
		<id>EAIJMS_EQR_SCNARIOCOPY_RUN</id>
		<class>com.hanjin.apps.alps.ees.eqr.common.ReceiveQueueIJMSProxy</class>
		<method>receiveEqr0002Copyrun</method>
	</target>
	<target>
		<id>EAIJMS_EQR_0011_RERUN</id>
		<class>com.hanjin.apps.alps.ees.eqr.common.ReceiveQueueIJMSProxy</class>
		<method>receiveEqr0011Rerun</method>
	</target>
	<target>
		<id>EAIJMS_EQR_ONEWAY_RERUN</id>
		<class>com.hanjin.apps.alps.ees.eqr.common.ReceiveQueueIJMSProxy</class>
		<method>receiveEqr0010Rerun</method>
	</target>
	<target>
		<id>EAIJMS_EQR_OPTIMIZATION_RUN</id>
		<class>com.hanjin.apps.alps.ees.eqr.common.ReceiveQueueIJMSProxy</class>
		<method>receiveEqr0049run</method>
	</target>
	<target>
		<id>EAIJMS_EQR_SENSITIVITT_RERUN</id>
		<class>com.hanjin.apps.alps.ees.eqr.common.ReceiveQueueIJMSProxy</class>
		<method>receiveEqr0065Rerun</method>
	</target>
	<target>
		<id>EAIJMS_EQR_OUTPUT_RUN</id>
		<class>com.hanjin.apps.alps.ees.eqr.common.ReceiveQueueIJMSProxy</class>
		<method>receiveEqr0050Outrun</method>
	</target>
	<target>
		<id>UBIZHJS_PITRS_USA204_ACK_T</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageUSATruckEdiWoAck</method>
	</target>
	<target>
		<id>EDIEUR_PITRS_EURSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageEurSoAckManage</method>
	</target>
	<target>
		<id>UBIZHJS_PITRS_EURSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageEurSoAckManage</method>
	</target>
	<target>
		<id>UBIZHJS_PITRS_KORSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageKorSoAckManage</method>
	</target>
	<target>
		<id>UBIZ2HJS_PITRS_USA204_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageUSATruckEdiWoAck</method>
	</target>

	<target>
		<id>UBIZHJS_PITRS_EURSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageEurSoAckManage</method>
	</target>
	<target>
		<id>UBIZHJS_PITRS_KORSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageKorSoAckManage</method>
	</target>
	<target>
		<id>UBIZHJS_PITRS_RAILWO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageUSARailWoAck</method>
	</target>
	<target>
		<id>UBIZHJS_PITRS_USA210_T</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageTRSTruckInvoice</method>
	</target>
	<target>
		<id>ESD075-0001</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageCanadaCustomsVesselManage</method>
	</target>
	<target>
		<id>ESD076-0001</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageCanadaCustoms</method>
	</target>

	<target>
		<id>FNS008-R003</id>
		<class>com.hanjin.bizcommon.erpcom.ReceiveQueueIJMSProxy</class>
		<method>receiveFNS008R003</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_001</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveAnnualTarget2Vbp</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_002</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveMonthlyDistribute</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_003</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveMonthlyCopyTargetVVD</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_004</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveMonthlyCreateSMRY</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_005</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveMonthlyNotifiedData</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_006</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveMonthlyProcess</method>
	</target>
	<target>
		<id>MNR001-0001</id>
		<class>com.hanjin.apps.alps.ees.mnr.servicesio.ReceiveEstimateFromCEDEXMQProxy</class>
		<method>receiveEstimateFromCEDEX</method>
	</target>
	<target>
		<id>ESD061-0001</id>
		<class>com.hanjin.apps.alps.vop.vsk.servicesio.SchedulePlanningOperationJMSProxy</class>
		<method>esd0610001ReceiveJMS</method>
	</target>
	<target>
		<id>ESD062-0001</id>
		<class>com.hanjin.apps.alps.vop.vsk.servicesio.SchedulePlanningOperationJMSProxy</class>
		<method>esd0620001ReceiveJMS</method>
	</target>
	<target>
		<id>FNS026_R001</id>
		<class>com.hanjin.apps.alps.ees.mst.servicesio.ContainerOnOffHireJMSProxy</class>
		<method>fNS026R001ReceiveJMS</method>
	</target>
	<target>
		<id>FNS012_R002</id>
		<class>com.hanjin.apps.alps.esm.fms.servicesio.TimeCharterInOutAccountingJMSProxy</class>
		<method>receiveSlipApprovalToAR</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSVSK_ACTSKD</id>
		<class>com.hanjin.apps.alps.vop.vsk.servicesio.ActualScheduleManagementMQProxy</class>
		<method>receiveEDIToTerminal</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSCGM_CHSS_MVMT</id>
		<class>com.hanjin.apps.alps.ees.cgm.servicesio.CgmChssMvmtMQProxy</class>
		<method>poolMvmtReceive</method>
	</target>
	<target>
		<id>FNS012-R001</id>
		<class>com.hanjin.apps.alps.fns.inv.servicesio.AccountReceivableInvoiceCreationJMSProxy</class>
		<method>modifyARInvoiceERPReturn</method>
	</target>

	<target>
		<id>UBIZHJS_ALPSINV_INVOIC</id>
		<class>com.hanjin.apps.alps.fns.inv.servicesio.AccountReceivableInvoiceCreationMQProxy</class>
		<method>interfaceTerminalARInvoiceToINV</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_007</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveYearlyProcess</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_ENTRY_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>udevhjsAlpsbkgEntryReceiveMQ</method>
	</target>
	<target>
		<id>FNS040-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageArRoutRnk</method>
	</target>
	<target>
		<id>FNS041-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageArFincDirConv</method>
	</target>
	<target>
		<id>FNS042-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageArMstRevVvd</method>
	</target>
	<target>
		<id>FNS044-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageArAgnStmtAgmt</method>
	</target>
	<target>
		<id>FNS045-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageApTax</method>
	</target>
	<target>
		<id>FNS046-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageApLuVal</method>
	</target>
	<target>
		<id>FNS048-0002</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageApPeriod</method>
	</target>
	<target>
		<id>FNS052-0001</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageApWorkplace</method>
	</target>
	<target>
		<id>AGT_CHG_ROUT_REF_SYNC</id>
		<class>com.hanjin.apps.alps.common.tableSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageAgtChgRout</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_EURBAPLIE</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.TerminalDocumentationProxy</class>
		<method>alpsbkgTEurbaplieReceiveMQ</method>
	</target>
	<target>
		<id>UBIZHJS_NISCGM_CHSSMVMT</id>
		<class>com.hanjin.apps.alps.ees.cgm.servicesio.CgmChssMvmtMQProxy</class>
		<method>poolMvmtReceive</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_EURCUS_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>udevhjsAlpsBkgTEurcusAckReceiveMQ</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_NACCS_REPLY</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsbkgNaccsReplyMQ</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSCTM_EQMVMT</id>
		<class>com.hanjin.apps.alps.ees.ctm.servicesio.CtmMovementGatenewMQProxy</class>
		<method>receiveEqMvmtEDIForGatenew</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_CNCUS_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsBkgTCncusAckReplyMQ</method>
	</target>
	<target>
		<id>EAIJMS_SAQ_008</id>
		<class>com.hanjin.apps.alps.esm.saq.serviceio.ReceiveQueueIJMSProxy</class>
		<method>receiveMonthlyDistribute</method>
	</target>
	<target>
		<id>EDI005_0001</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.BookingMasterDataJMSProxy</class>
		<method>receiveBkgEdiTrdPrnrSubLnk</method>
	</target>
	<target>
		<id>EDI006_0001</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.BookingMasterDataJMSProxy</class>
		<method>receiveBkgEdiSubLnkMsg</method>
	</target>
	<target>
		<id>EDI007_0001</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.BookingMasterDataJMSProxy</class>
		<method>receiveBkgEdiPrnrPortLane</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_KRCUS_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>udevhjsAlpsbkgKrcusReceiveMQ</method>
	</target>
	<target>
		<id>FNS010-0002</id>
		<class>com.hanjin.bizcommon.erpcom.ReceiveQueueIJMSProxy</class>
		<method>receiveFNS0100002</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_CLL_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.TerminalDocumentationProxy</class>
		<method>alpsbkgCllAckMQ</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_USTMNL_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.GeneralBookingConductMQProxy</class>
		<method>receiptUsaTmlEdiAck</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_EDO</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.InboundDocumentationProxy</class>
		<method>receiptEdo</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_EDO_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.InboundDocumentationProxy</class>
		<method>receiptEdoLog</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSCGM_CHSS_INV</id>
		<class>com.hanjin.apps.alps.ees.cgm.servicesio.CgmChssMvmtMQProxy</class>
		<method>poolMnrInvoiceImport</method>
	</target>
	<target>
		<id>ESM067_0001</id>
		<class>com.hanjin.apps.alps.fns.inv.servicesio.AccountReceivableInvoiceCreationJMSProxy</class>
		<method>interfaceDomesticARInvoiceToINV</method>
	</target>
	<target>
		<id>VSL_PORT_SKD_SYNC</id>
		<class>com.hanjin.apps.alps.esm.fms.servicesio.TimeCharterInOutAccountingJMSProxy</class>
		<method>receiveVvd</method>
	</target>
	<target>
		<id>MDM060-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmCarrier</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSBKG_EURDG_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.TerminalDocumentationProxy</class>
		<method>udevhjsAlpsAkgTEurDgAckReceiveMQ</method>
	</target>
	<target>
		<id>ESD031-0001</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDISetupJMSProxy</class>
		<method>syncEdi_cgo_stnd_sts</method>
	</target>
	<target>
		<id>ESD032-0001</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDISetupJMSProxy</class>
		<method>syncEdi_group</method>
	</target>
	<target>
		<id>ESD033-0001</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDISetupJMSProxy</class>
		<method>syncEdi_grp_cgo</method>
	</target>
	<target>
		<id>ESD034-0001</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDISetupJMSProxy</class>
		<method>syncEdi_grp_cust</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSSCE_EQCLM</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDIReceiveMQProxy</class>
		<method>createClmdata</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSMNR_WESTIM</id>
		<class>com.hanjin.apps.alps.ees.mnr.servicesio.ReceiveEstimateFromCEDEXMQProxy</class>
		<method>receiveEstimateFromCEDEX</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSSCE_322</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDIReceiveMQProxy</class>
		<method>createEDI322data</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSTRS_RAILWO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageUSARailWoAck</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSTRS_EURSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageEurSoAckManage</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSTRS_KORSO_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageKorSoAckManage</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSTRS_USA204_ACK</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageUSATruckEdiWoAck</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSTRS_USA210</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageTRSTruckInvoice</method>
	</target>
	<target>
		<id>UBIZHJS_ALPSTRS_USA214</id>
		<class>com.hanjin.apps.alps.esd.sce.servicesio.EDIReceiveMQProxy</class>
		<method>createEDI214data</method>
	</target>
	<!-- target>
		<id>UBIZHJS_ALPSTES_EDI</id>
		<class>com.hanjin.apps.alps.esd.tes.common.tesinterface.TESInterfaceIJMSProxy</class>
		<method>createEDIinvoice</method>
	</target-->
	<target>
		<id>MDM061-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmDaylight</method>
	</target>
	<target>
		<id>EDI011_0001</id>
		<class>com.hanjin.apps.alps.vop.vsk.servicesio.SchedulePlanningOperationJMSProxy</class>
		<method>esdSettingReceiveJMS</method>
	</target>
	<target>
		<id>MDM023-0001</id>
		<class>com.hanjin.apps.alps.common.mdmSync.jms.ReceiveQueueIJMSProxy</class>
		<method>manageMdmVslBlk</method>
	</target>
	<target>
		<id>ESM068_0001</id>
		<class>com.hanjin.apps.alps.esm.pri.servicesio.SCProposalJMSProxy</class>
		<method>receiveNISProposalInfo</method>
	</target>
	<target>
		<id>COM005_R001</id>
		<class>com.hanjin.apps.alps.cps.cni.servicesio.ContainerCargoClaimJMSProxy</class>
		<method>com005R001ReceiveJMS</method>
	</target>
	<target>
		<id>ESD040-0001</id>
		<class>com.hanjin.apps.alps.esd.trs.servicesio.TRSInterfaceEAIProxy</class>
		<method>manageCustPreference</method>
	</target>
	
	<!-- 2010/09/10 Request by Tae-Kyoung KIM (ISA) -->	
	<target>
        <id>UBIZHJS_ALPSBKG_OUTBOUND_CHN</id>
        <class>com.hanjin.apps.alps.esm.bkg.servicesio.BookingReportProxy</class>
        <method>chnEdiReceiveMQ</method>
    </target>
	<!-- 2010/12/23 Request by YONG TAE LEE (ISA) -->	
    <target>
		<id>UBIZHJS_ALPSBKG_EUR24_ACK</id>
		<class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
		<method>alpsBkgEur24ReplyMQ</method>
	</target>
	<!-- 2010/12/30 Request by SUK JOON LEE -->	
	<target>
        <id>UBIZHJS_ALPSINV_APERAK</id>         
        <class>com.hanjin.apps.alps.fns.inv.servicesio.AccountReceivableInvoiceMgtMQProxy</class>                    
        <method>receiveEdiFromGlovis</method>
    </target>
	<!-- 2010/12/30 Request by SEUNG JIN JUN -->
	<target>
        <id>UBIZHJS_ALPSBKG_SIMPLE</id>
        <class>com.hanjin.apps.alps.esm.bkg.servicesio.ExcelEdiMQProxy</class>
        <method>receiptXterRqst</method>
    </target>
	<!-- 2011/09/29 Request by Jong-Yun KYOUNG -->
    <target>
           <id>UBIZHJS_ALPSBKG_MEDCUSRPL</id>
           <class>com.hanjin.apps.alps.esm.bkg.servicesio.CustomsDeclarationProxy</class>
           <method>alpsbkgSpainCRNReceiveMQ</method>
    </target>
    
   <!-- added by 9011644 (BST) 2012 01 11 start-->
    <target>
            <id>UBIZHJS_ALPSBKG_PSADG_ACK</id>
            <class>com.hanjin.apps.alps.esm.bkg.servicesio.TerminalDocumentationProxy</class> 
            <method>udevhjsAlpsAkgTPSADGDgAckReceiveMQ</method>
    </target>
     <!-- added by 9011644 (BST) 2012 01 11 end -->
  
        <!-- added by 9011644 (BST) 2012 03 06 start-->
    <target>
            <id>UBIZHJS_ALPSTES_PDF</id>
            <class>com.hanjin.apps.alps.esd.tes.common.tesinterface.TESInterfaceIJMSProxy</class> 
            <method>saveEDIPDFfile</method>
    </target>
     <!-- added by 9011644 (BST) 2012 03 06 end -->
    
    
    <!--  added by 9011644 ( BST ) EAI new connect start
    	# 2012 02 16 VMS006_0001 delete 
     -->
    <target>
            <id>VMS004_0001</id>
            <class>com.hanjin.apps.alps.vop.fcm.servicesio.VesselReportJMSProxy</class> 
            <method>vopFcm0001ReceiveJMS</method>
    </target>
    <target>
            <id>VMS005_0001</id>
            <class>com.hanjin.apps.alps.vop.fcm.servicesio.VesselReportJMSProxy</class> 
            <method>vopFcm0002ReceiveJMS</method>
    </target>
    <target>
            <id>VMS007_0001</id>
            <class>com.hanjin.apps.alps.vop.fcm.servicesio.VesselReportJMSProxy</class> 
            <method>vopFcm0004ReceiveJMS</method>
    </target>
	<!--  added by 9011644 ( BST ) EAI new connect end -->
	
	<!-- requested by 2014505 2015 08 06 EAI new connect start -->
    <target>
            <id>VMS008_0001</id>
            <class>com.hanjin.apps.alps.vop.vsk.servicesio.VesselPassagePlanReceiveManagementJMSProxy</class>
            <method>receivePassagePlanFromVMS</method>
    </target>
    <!-- requested by 2014505 2015 08 06 EAI new connect end -->
	
	<!-- added by 2004611 (BST) 2012 04 10 start-->
    <target>
			<id>UBIZHJS_ALPSBKG_SEANACCS_BKGACK</id>
			<class>com.hanjin.apps.alps.esm.bkg.servicesio.JapanTerminalProxy</class>
			<method>alpsBkgTerminalNaccsReplyMQ</method>
 	</target>